name: asigar_lp
description: A resource to help developers evaluate and use Flutter.

version: 2.3.0+020300

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  # intl:
  # intl_translation:
  # flutter_localized_locales: ^1.1.0
  # cupertino_icons: ^0.1.3
  # rally_assets: ^2.0.0
  # meta:
  # scoped_model:
  # shrine_images: ^1.1.2
  # flare_flutter: ^2.0.2
  # url_launcher: ^5.1.6
  # shared_preferences: ^0.5.4
  # collection: ^1.14.0
  # flutter_gallery_assets: ^0.1.9
  # package_info: ^0.4.0
  # google_fonts: ^0.4.0
  font_awesome_flutter: ^8.5.0
  flutter_icons: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  grinder: ^0.8.0
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:
  assets:
    - fonts/google_fonts/
    - assets/demos/
    - assets/studies/
    - assets/icons/cupertino/
    - assets/icons/material/
    - assets/icons/reference/
    - assets/icons/settings/
    - assets/logo/
    - assets/splash_effects/
    - assets/crane/logo/
    - assets/crane/destinations/
    - assets/fortnightly/

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: fonts/GalleryIcons.ttf
    - family: Cousine
      fonts:
        - asset: fonts/Cousine-Bold.ttf
          weight: 700
        - asset: fonts/Cousine-Regular.ttf
          weight: 400
        - asset: fonts/Cousine-BoldItalic.ttf
          weight: 600
        - asset: fonts/Cousine-Italic.ttf
          weight: 300
          # style: italic
